Traceback (most recent call last):
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/shappiron/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from rpy2 import robjects
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri, Formula
import rpy2.robjects.numpy2ri
pandas2ri.activate()
robjects.numpy2ri.activate()
from rpy2.robjects.conversion import localconverter
from rpy2.rinterface_lib.embedded import RRuntimeError
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [8][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrpy2[39;00m [38;5;28;01mimport[39;00m robjects
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrpy2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrobjects[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpackages[39;00m [38;5;28;01mimport[39;00m importr
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrpy2[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrobjects[39;00m [38;5;28;01mimport[39;00m pandas2ri, Formula

[0;31mModuleNotFoundError[0m: No module named 'rpy2'
ModuleNotFoundError: No module named 'rpy2'

